package dhs_ice.dataprovisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class request implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public request() {
    }

}