package dhs_ice.dataprovisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class request implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Badge Number")
   private java.lang.String badgeNumber;
   @org.kie.api.definition.type.Label("Project Name")
   private java.lang.String projectName;
   @org.kie.api.definition.type.Label("Date Active")
   private java.util.Date dateActive;
   @org.kie.api.definition.type.Label("Project Description")
   private java.lang.String projectDescription;
   @org.kie.api.definition.type.Label("ICM")
   private java.lang.Boolean icm;
   @org.kie.api.definition.type.Label("FALCON")
   private java.lang.Boolean falcon;
   @org.kie.api.definition.type.Label("EID")
   private java.lang.Boolean eid;
   @org.kie.api.definition.type.Label("FINCEN")
   private java.lang.Boolean fincen;
   @org.kie.api.definition.type.Label("FIS")
   private java.lang.Boolean fis;
   @org.kie.api.definition.type.Label("SEACATS")
   private java.lang.Boolean seacats;
   @org.kie.api.definition.type.Label("SEN")
   private java.lang.Boolean sen;
   @org.kie.api.definition.type.Label("TLS")
   private java.lang.Boolean tls;

   @org.kie.api.definition.type.Label("Shared File Path")
   private java.lang.String filepath;

   @org.kie.api.definition.type.Label("Upload Document")
   private java.lang.Byte document;

   @org.kie.api.definition.type.Label("Reason for Rejection")
   private java.lang.String rejectionReason;

   @org.kie.api.definition.type.Label("Request Completed")
   private java.lang.Boolean completed;

   @org.kie.api.definition.type.Label("Virtual Database Details")
   private java.lang.String vdbDetails;

   @org.kie.api.definition.type.Label(value = "Reason for Changes")
   private java.lang.String reasonForChange;

   public request()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getBadgeNumber()
   {
      return this.badgeNumber;
   }

   public void setBadgeNumber(java.lang.String badgeNumber)
   {
      this.badgeNumber = badgeNumber;
   }

   public java.lang.String getProjectName()
   {
      return this.projectName;
   }

   public void setProjectName(java.lang.String projectName)
   {
      this.projectName = projectName;
   }

   public java.util.Date getDateActive()
   {
      return this.dateActive;
   }

   public void setDateActive(java.util.Date dateActive)
   {
      this.dateActive = dateActive;
   }

   public java.lang.String getProjectDescription()
   {
      return this.projectDescription;
   }

   public void setProjectDescription(java.lang.String projectDescription)
   {
      this.projectDescription = projectDescription;
   }

   public java.lang.Boolean getIcm()
   {
      return this.icm;
   }

   public void setIcm(java.lang.Boolean icm)
   {
      this.icm = icm;
   }

   public java.lang.Boolean getFalcon()
   {
      return this.falcon;
   }

   public void setFalcon(java.lang.Boolean falcon)
   {
      this.falcon = falcon;
   }

   public java.lang.Boolean getEid()
   {
      return this.eid;
   }

   public void setEid(java.lang.Boolean eid)
   {
      this.eid = eid;
   }

   public java.lang.Boolean getFincen()
   {
      return this.fincen;
   }

   public void setFincen(java.lang.Boolean fincen)
   {
      this.fincen = fincen;
   }

   public java.lang.Boolean getFis()
   {
      return this.fis;
   }

   public void setFis(java.lang.Boolean fis)
   {
      this.fis = fis;
   }

   public java.lang.Boolean getSeacats()
   {
      return this.seacats;
   }

   public void setSeacats(java.lang.Boolean seacats)
   {
      this.seacats = seacats;
   }

   public java.lang.Boolean getSen()
   {
      return this.sen;
   }

   public void setSen(java.lang.Boolean sen)
   {
      this.sen = sen;
   }

   public java.lang.Boolean getTls()
   {
      return this.tls;
   }

   public void setTls(java.lang.Boolean tls)
   {
      this.tls = tls;
   }

   public java.lang.String getFilepath()
   {
      return this.filepath;
   }

   public void setFilepath(java.lang.String filepath)
   {
      this.filepath = filepath;
   }

   public java.lang.Byte getDocument()
   {
      return this.document;
   }

   public void setDocument(java.lang.Byte document)
   {
      this.document = document;
   }

   public java.lang.String getRejectionReason()
   {
      return this.rejectionReason;
   }

   public void setRejectionReason(java.lang.String rejectionReason)
   {
      this.rejectionReason = rejectionReason;
   }

   public java.lang.Boolean getCompleted()
   {
      return this.completed;
   }

   public void setCompleted(java.lang.Boolean completed)
   {
      this.completed = completed;
   }

   public java.lang.String getVdbDetails()
   {
      return this.vdbDetails;
   }

   public void setVdbDetails(java.lang.String vdbDetails)
   {
      this.vdbDetails = vdbDetails;
   }

   public java.lang.String getReasonForChange()
   {
      return this.reasonForChange;
   }

   public void setReasonForChange(java.lang.String reasonForChange)
   {
      this.reasonForChange = reasonForChange;
   }

   public request(java.lang.String name, java.lang.String badgeNumber,
         java.lang.String projectName, java.util.Date dateActive,
         java.lang.String projectDescription, java.lang.Boolean icm,
         java.lang.Boolean falcon, java.lang.Boolean eid,
         java.lang.Boolean fincen, java.lang.Boolean fis,
         java.lang.Boolean seacats, java.lang.Boolean sen,
         java.lang.Boolean tls, java.lang.String filepath,
         java.lang.Byte document, java.lang.String rejectionReason,
         java.lang.Boolean completed, java.lang.String vdbDetails,
         java.lang.String reasonForChange)
   {
      this.name = name;
      this.badgeNumber = badgeNumber;
      this.projectName = projectName;
      this.dateActive = dateActive;
      this.projectDescription = projectDescription;
      this.icm = icm;
      this.falcon = falcon;
      this.eid = eid;
      this.fincen = fincen;
      this.fis = fis;
      this.seacats = seacats;
      this.sen = sen;
      this.tls = tls;
      this.filepath = filepath;
      this.document = document;
      this.rejectionReason = rejectionReason;
      this.completed = completed;
      this.vdbDetails = vdbDetails;
      this.reasonForChange = reasonForChange;
   }

}